server:
  port: 9099
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/shiro_boot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    timeout: 0
mybatis:
  type-aliases-package: com.home.mail.domain